### ISSUE TITLE
Version 0.3.3 in Python2

### ISSUE THREAD

**Issue by luthor112** [KimiNewt/pyshark#47]
My code from version 0.2.7 doesn't work with version 0.3.3, although the docs on the net doesn't seem to have changed.
Wasn't 0.3.3 meant for Python3? (Just guessing from the number.)

This is what I get when using pyshark 0.3.3:
Exception AttributeError: "'FileCapture' object has no attribute 'running_processes'" in  ignored
[...]
    capture = pyshark.FileCapture(input_file=capture_file, lazy=True, keep_packets=False)
TypeError: __init__() got an unexpected keyword argument 'lazy'

Everything works fine in 0.2.7.

Cool module.
