### ISSUE TITLE
Not able to access packet.ip.dst attribute

### ISSUE THREAD

**Issue by lordlabakdas** [KimiNewt/pyshark#194]
hello,

I have the below code:
```
capture = pyshark.LiveCapture(interface='eth0')
for packet in capture.sniff_continuously(packet_count=5):
    print packet.ip.src
```
I am trying to access `packet.ip.src` or `packet.ip.dst` but both do not seem to be working. I get the below error when I try:
```
AttributeError: 'PacketSummary' object has no attribute 'ip'
```
When I try `packet['ip'].src`, I get `TypeError: 'PacketSummary' object has no attribute '__getitem__'`

I am working with `pyshark==0.3.7.2` on an `Ubuntu 14.04` with `python 2.7`.

Am I missing something?

**Comment by KimiNewt** [comment]
That does not seem to be the code you're running, as PacketSummary objects will only be used if you've used `only_summaries=True` in the constructor. Can you confirm that you're running that version of the code?

**Comment by SparshLadani** [comment]
@KimiNewt 

this is the code snippet on what im working on right now:

current_capture = pyshark.LiveCapture(interface='eth0', output_file="Suspicious_Capture.pcap", debug=True)
    for packet in current_capture.sniff_continuously():
        try:
            capture_list = []
            capture_list.append(packet.sniff_timestamp, packet.ip.src, packet.ip.dest, packet.highest_layer, packet.length)
            model_output = randomforest_model.predict(np.array(capture_list).reshape(1, -1))
            if model_output:
                break

        except Exception as e:
            print(f"Error processing the packet: {e}")
    current_capture.close()

What if i want to capture ip address (Source and destination) reagrdless of the protocol used?
