### ISSUE TITLE
Does not work on Python 3.14

### ISSUE THREAD

**Issue by nyanpasu64** [KimiNewt/pyshark#758]
**Describe the bug**
When I run the code on Arch Linux, I get error `RuntimeError: There is no current event loop in thread 'MainThread'.`. When I construct an event loop with:

```python
loop = asyncio.new_event_loop() # Create a new event loop in the thread
asyncio.set_event_loop(loop) # Set the new event loop as the current loop
```

I get error `AttributeError: module 'asyncio' has no attribute 'set_child_watcher'`. It appears this method was removed in Python 3.14.

**To Reproduce**
```python
import asyncio
import pyshark

def main():
    loop = asyncio.new_event_loop() # Create a new event loop in the thread
    asyncio.set_event_loop(loop) # Set the new event loop as the current loop

    cap = pyshark.FileCapture('switch-usb.pcap')
    print(cap)
    print(cap[0])


if __name__ == "__main__":
    main()
```

**Expected behavior**
Doesn't crash

**Versions (please complete the following information):**
 - OS: Arch Linux
 - pyshark version: 0.6, Git

**Comment by nyanpasu64** [comment]
Ahh there's an open PR at #755. I have not tested it.
